[project]
name = "pips-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "cachetools>=7.0.1",
    "click>=8.3.1",
    "fastapi[standard]>=0.129.2",
    "psutil>=7.2.2",
    "sqlalchemy>=2.0.50",
    "typer>=0.24.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.1",
]

[tool.ruff]
line-length = 120
format.quote-style = "single"

[tool.ruff.lint]
extend-select = ["I"]
