"""puzzle state

Revision ID: 2fdb4ad49e29
Revises: 86fd97ef945f
Create Date: 2026-06-26 21:21:35.273177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fdb4ad49e29'
down_revision: Union[str, Sequence[str], None] = '86fd97ef945f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle_state',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('puzzle_title', sa.Text(), nullable=False),
    sa.Column('puzzle_version', sa.Integer(), nullable=False),
    sa.Column('placements', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('placements_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_title', 'puzzle_version'], ['puzzle.title', 'puzzle.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('placement_hash', 'puzzle_state', ['puzzle_title', 'puzzle_version', 'placements_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('placement_hash', table_name='puzzle_state')
    op.drop_table('puzzle_state')
    # ### end Alembic commands ###
