"""blob state

Revision ID: 074b175ca825
Revises: e5555698143e
Create Date: 2026-07-05 17:58:01.550763

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '074b175ca825'
down_revision: Union[str, Sequence[str], None] = 'e5555698143e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('placement_hash'), table_name='puzzle_state')
    op.drop_column('puzzle_state', 'placements')
    op.drop_column('puzzle_state', 'placements_hash')
    op.add_column('puzzle_state', sa.Column('placements', sa.LargeBinary(), nullable=False))
    op.create_unique_constraint(None, 'puzzle_state', ['placements', 'puzzle_title', 'puzzle_version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('puzzle_state_placements_puzzle_title_puzzle_version_key', 'puzzle_state', type_='unique')
    op.drop_column('puzzle_state', 'placements')
    op.add_column('puzzle_state', sa.Column('placements_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column(
        'puzzle_state', sa.Column('placements', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False)
    )
    op.create_index(
        op.f('placement_hash'), 'puzzle_state', ['puzzle_title', 'puzzle_version', 'placements_hash'], unique=False
    )
    # ### end Alembic commands ###
