"""convert node status to enum

Revision ID: 03443288c210
Revises: 074b175ca825
Create Date: 2026-08-16 09:02:08.336590

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '03443288c210'
down_revision: Union[str, Sequence[str], None] = '074b175ca825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'solver_node',
        'status',
        existing_type=sa.TEXT(),
        type_=sa.Enum('WON', 'LOST', 'INCOMPLETE', 'UNVISITED', name='solvernodestatus', native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'solver_node',
        'status',
        existing_type=sa.Enum('WON', 'LOST', 'INCOMPLETE', 'UNVISITED', name='solvernodestatus', native_enum=False),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
