"""puzzle-model

Revision ID: 86fd97ef945f
Revises:
Create Date: 2026-06-22 21:03:19.444918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '86fd97ef945f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'puzzle',
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('background', postgresql.ARRAY(sa.SMALLINT()), nullable=False),
        sa.Column('constraints', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=False),
        sa.Column('dominoes', postgresql.ARRAY(sa.SMALLINT()), nullable=False),
        sa.PrimaryKeyConstraint('title', 'version'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle')
    # ### end Alembic commands ###
