"""solver models

Revision ID: e5555698143e
Revises: 2fdb4ad49e29
Create Date: 2026-07-03 21:00:05.603713

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e5555698143e'
down_revision: Union[str, Sequence[str], None] = '2fdb4ad49e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'solver',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('puzzle_title', sa.Text(), nullable=False),
        sa.Column('puzzle_version', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error', sa.String(), nullable=True),
        sa.Column('peak_memory_usage_mb', sa.Float(), nullable=True),
        sa.Column('iterations', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('NOT_RUN', 'NO_SOLUTIONS', 'ERROR', 'SOLVED', name='solverstatus', native_enum=False),
            nullable=False,
        ),
        sa.Column('lock', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['puzzle_title', 'puzzle_version'],
            ['puzzle.title', 'puzzle.version'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('puzzle_title', 'puzzle_version'),
    )
    op.create_table(
        'solver_node',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('num_placements', sa.Integer(), nullable=False),
        sa.Column('solver_id', sa.Integer(), nullable=False),
        sa.Column('puzzle_state_id', sa.BigInteger(), nullable=False),
        sa.Column('status', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ['puzzle_state_id'],
            ['puzzle_state.id'],
        ),
        sa.ForeignKeyConstraint(['solver_id'], ['solver.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('solver_id', 'puzzle_state_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solver_node')
    op.drop_table('solver')
    # ### end Alembic commands ###
